/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VerifyLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete: operations["DeleteUser"];
        options?: never;
        head?: never;
        patch: operations["EditUser"];
        trace?: never;
    };
    "/il/get-cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/accommodations/{hotelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetIntegrationHotelAccommodations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/mapped/{integrationName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAllMapped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetInterlookAndIntegrationHotels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FindHotelByname"];
        put?: never;
        post?: never;
        delete: operations["DeleteHotel"];
        options?: never;
        head?: never;
        patch: operations["HotelMap"];
        trace?: never;
    };
    "/bookings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SearchBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ConfirmBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DenyBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetBookings"];
        put?: never;
        post: operations["SendBookings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accommodations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetVariants"];
        put?: never;
        post: operations["CreateHotelVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["HotelMapProperties"];
        trace?: never;
    };
    "/accommodations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DeleteHotelAccommodationMap"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        IUserToken: {
            _id: string;
            email: string;
            name: string;
            isAdmin: boolean;
        };
        IUser: {
            _id: string;
            email: string;
            name: string;
            password: string;
            isAdmin: boolean;
        };
        HotelResponse: {
            /** Format: double */
            hotelId: number;
            hotelName: string;
            settings: {
                serverName: string;
                /** Format: double */
                hotelServerId: number;
                hotelServer: string;
            };
            mapped?: boolean;
        };
        IHotel: {
            /** Format: double */
            _id: number;
            name: string;
            resort: string;
            code: string;
            category: string;
            /** Format: double */
            regionId: number;
            /** Format: double */
            resortId: number;
            integrationSettings?: {
                hotelId: string;
                apiName: string;
            } & {
                [key: string]: unknown;
            };
        };
        IMessage: {
            id: string;
            sender?: string;
            isRead: boolean;
            text: string;
            isOutgoing: boolean;
            dateCreate: string;
        };
        ITourist: {
            name: string;
            birthDate?: string;
            sex?: string;
            /** Format: double */
            hotelServiceId?: number;
        };
        ICostOffersInfo: {
            costOfferName: string;
            /** Format: double */
            costOfferDuration: number;
            costOfferDateBegin: string;
            costOfferDateEnd: string;
        };
        IHotelServiceBooking: {
            /** Format: double */
            serviceId: number;
            serviceName: string;
            bookingCode: string;
            /** Format: double */
            hotelId: number;
            hotel: string;
            /** Format: double */
            pansionId: number;
            pansion: string;
            /** Format: double */
            roomTypeId: number;
            roomType: string;
            roomMapCode: string;
            /** Format: double */
            roomAccommodationId: number;
            roomAccommodation: string;
            /** Format: double */
            roomCategoryId: number;
            roomCategory: string;
            confirmationNumber?: string;
            checkIn: string;
            checkOut: string;
            status: string;
            note?: string;
            tourists: components["schemas"]["ITourist"][];
            priceRemark?: string;
            costOffersInfo: components["schemas"]["ICostOffersInfo"][];
            log?: {
                /** @enum {string} */
                integrationStatus?: "wait" | "confirmed" | "denied";
                manual?: {
                    [key: string]: {
                        confirmationNumber?: string;
                        message: string;
                        bookingNumber: string;
                    };
                };
                response: unknown;
                send: unknown;
                /** Format: date-time */
                sendDate?: string;
            };
        };
        IFlight: {
            flightArr: string;
            flightDep: string;
        };
        IBooking: {
            _id?: string;
            bookingName: string;
            /** Format: double */
            bookingId: number;
            action: string;
            creationDate?: string;
            cancelDate?: string;
            changeDate?: string;
            /** Format: double */
            marketId: number;
            marketName: string;
            messages: components["schemas"]["IMessage"][];
            hotelServices: components["schemas"]["IHotelServiceBooking"][];
            flightInfo?: components["schemas"]["IFlight"];
            /** Format: date-time */
            dateInputed?: string;
        };
        IBoard: {
            _id?: string;
            /** Format: double */
            boardId: number;
            boardName: string;
            integrationCode?: string;
        };
        IRoom: {
            _id?: string;
            /** Format: double */
            roomTypeId: number;
            roomTypeName: string;
            /** Format: double */
            roomCategoryId: number;
            roomCategoryName?: string;
            integrationCode?: string;
        };
        IAccommodationMap: {
            /** Format: double */
            _id: number;
            hotelName: string;
            integrationName: string;
            boards: {
                [key: string]: components["schemas"]["IBoard"];
            };
            rooms: {
                [key: string]: components["schemas"]["IRoom"];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                    email: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        userData: components["schemas"]["IUserToken"];
                        token: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    VerifyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IUserToken"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    GetAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IUser"][];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isAdmin: boolean;
                    password: string;
                    name: string;
                    email: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    _id: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    EditUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isAdmin?: boolean;
                    password?: string;
                    name?: string;
                    email: string;
                    _id: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    GetCities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    GetIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        displayName: string;
                        name: string;
                    }[];
                };
            };
        };
    };
    GetIntegrationHotelAccommodations: {
        parameters: {
            query: {
                integrationName: string;
            };
            header?: never;
            path: {
                hotelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        boards: string[];
                        rooms: string[];
                    };
                };
            };
        };
    };
    GetAllMapped: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integrationName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    GetInterlookAndIntegrationHotels: {
        parameters: {
            query: {
                integrationName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        interlookHotelsApi?: unknown;
                        integratedHotels?: unknown;
                        interlookHotels: unknown[];
                        integrationHotels: unknown[];
                    } | {
                        interlookHotels?: unknown;
                        integrationHotels?: unknown;
                        interlookHotelsApi: unknown;
                        integratedHotels: (components["schemas"]["HotelResponse"] & {
                            mapped: boolean;
                        })[];
                    };
                };
            };
        };
    };
    FindHotelByname: {
        parameters: {
            query: {
                integrationName?: string;
                hotelName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IHotel"][];
                };
            };
        };
    };
    DeleteHotel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    integrationName: string;
                    /** Format: double */
                    hotelId: number;
                };
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HotelMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: double */
                    hotelId: number;
                    /** Format: double */
                    integrationValue: number;
                    integrationName: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IHotel"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    SearchBooking: {
        parameters: {
            query: {
                skip: number;
                limit: number;
                isCreateDate: boolean;
                booking: string;
                dateTo: string;
                dateFrom: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        count: number;
                        bookings: components["schemas"]["IBooking"][];
                    };
                };
            };
        };
    };
    ConfirmBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    confirmationNumber: string;
                    bookingNumber: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    DenyBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    bookingNumber: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    GetBookings: {
        parameters: {
            query: {
                next: boolean;
                status: "new" | "change" | "cancel";
                integrationName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IBooking"][];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    SendBookings: {
        parameters: {
            query: {
                flag: "new" | "change" | "cancel";
                integrationName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IBooking"][];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        cancelled: number;
                        /** Format: double */
                        notConfirmed: number;
                        /** Format: double */
                        confirmed: number;
                        /** Format: double */
                        sended: number;
                        /** Format: double */
                        errors: number;
                    };
                };
            };
        };
    };
    GetVariants: {
        parameters: {
            query: {
                integrationName: string;
                ilCode: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IAccommodationMap"];
                };
            };
        };
    };
    CreateHotelVariant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    integrationName: string;
                    checkOut: string;
                    checkIn: string;
                    /** Format: double */
                    ilCode: number;
                };
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    HotelMapProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    integrationName: string;
                    /** Format: double */
                    hotelId: number;
                    rooms: {
                        [key: string]: components["schemas"]["IRoom"];
                    };
                    boards: {
                        [key: string]: components["schemas"]["IBoard"];
                    };
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IAccommodationMap"];
                };
            };
        };
    };
    DeleteHotelAccommodationMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
